import DruidImage from '../src/images/covers/druid.jpeg';
import ZeusImage from '../src/images/covers/zeus.jpg';

export const musicList = [
  {
    id: 'zeus',
    title: 'Zeus',
    year: 2017,
    downloadLink: 'http://www.google.com',
    image: ZeusImage,
    type: 'album',
  },
  {
    id: 'druid-lizard',
    title: 'Druid Lizard',
    year: 2015,
    downloadLink: 'http://www.google.com',
    image: DruidImage,
    type: 'single',
  },
  {
    id: 'blah',
    title: 'Zeus',
    year: 2017,
    downloadLink: 'http://www.google.com',
    image: ZeusImage,
    type: 'album',
  },
  {
    id: 'bagee',
    title: 'Druid Lizard',
    year: 2015,
    downloadLink: 'http://www.google.com',
    image: DruidImage,
    type: 'single',
  },
  {
    id: 'rewrew',
    title: 'Druid Lizard',
    year: 2015,
    downloadLink: 'http://www.google.com',
    image: DruidImage,
    type: 'single',
  },
  {
    id: 'rewrewe',
    title: 'Druid Lizard',
    year: 2015,
    downloadLink: 'http://www.google.com',
    image: DruidImage,
    type: 'single',
  },
  {
    id: 'zeus',
    title: 'Zeus',
    year: 2017,
    downloadLink: 'http://www.google.com',
    image: ZeusImage,
    type: 'album',
  },
  {
    id: 'druid-lizard',
    title: 'Druid Lizard',
    year: 2015,
    downloadLink: 'http://www.google.com',
    image: DruidImage,
    type: 'single',
  },
  {
    id: 'blah',
    title: 'Zeus',
    year: 2017,
    downloadLink: 'http://www.google.com',
    image: ZeusImage,
    type: 'album',
  },
  {
    id: 'bagee',
    title: 'Druid Lizard',
    year: 2015,
    downloadLink: 'http://www.google.com',
    image: DruidImage,
    type: 'single',
  },
  {
    id: 'rewrew',
    title: 'Druid Lizard',
    year: 2015,
    downloadLink: 'http://www.google.com',
    image: DruidImage,
    type: 'single',
  },
  {
    id: 'rewrewe',
    title: 'Druid Lizard',
    year: 2015,
    downloadLink: 'http://www.google.com',
    image: DruidImage,
    type: 'single',
  },
];
